# Generated by Django 5.0.7 on 2024-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KirimChiqim', '0002_categories_hisobtype_inputoutputtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Kirim'), ('OUT', 'Chiqim')], max_length=3),
        ),
        migrations.DeleteModel(
            name='InputOutputType',
        ),
    ]
